version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - aws s3 sync ./static-site s3://awsquizlabs.com
      - echo List bucket files
      - aws s3 ls s3://awsquizlabs.com
    finally:
      - echo This always runs even if the update or install command fails